# Generated by Django 5.0.1 on 2024-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200, unique=True)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('fixed_price', models.IntegerField()),
                ('min_hprice', models.IntegerField()),
                ('max_hprice', models.IntegerField()),
                ('trading_firm', models.TextField()),
                ('crawled_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.TextField()),
                ('firm_link', models.TextField()),
            ],
        ),
    ]
